<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <WarningsNotAsErrors>$(WarningsNotAsErrors);NU1903;NU1902;NU1901;NU1904</WarningsNotAsErrors>
    <NoWarn>$(NoWarn);NU1903;NU1902;NU1901;NU1904</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="AWSSDK.S3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Nimpression.Application\Nimpression.Application.csproj" />
    <ProjectReference Include="..\..\Nimpression.Infrastructure\Nimpression.Infrastructure.csproj" />
  </ItemGroup>

</Project>